doctrine_migrations:
      # List of namespace/path pairs to search for migrations, at least one required
      migrations_paths:
        'App\Migrations': 'src/Migrations'

      # Entity manager to use for migrations. This overrides the "connection" setting.
      em: default

      storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
          table_name: 'migration_versions'

      # Path to your custom migrations template
      custom_template: ~

      # Run all migrations in a transaction.
      all_or_nothing: false
      # Adds an extra check in the generated migrations to ensure that is executed on the same database type.
      check_database_platform: true
